# Dockerfile para C1
FROM ubuntu:16.10

# Cambiar los repositorios a old-releases
RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

# Actualizar repositorios e instalar openssh-client
RUN apt-get update && apt-get install -y openssh-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN apt update && apt install -y iputils-ping


CMD ["bash"]
